### ISSUE TITLE
Endianness war [SPARC]

### ISSUE THREAD

**Issue by tankf33der** [codr7/libc7#2]
Lets run tests.c under different endianness you develop on. 

Welcome to hell. Enjoy and have fun.

```
$ file ./a.out 
./a.out:        ELF 64-bit MSB executable SPARCV9 Version 1, dynamically linked, not stripped
$ ./a.out 
Bus Error (core dumped)
$ gdb ./a.out core 
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "sparcv9-sun-solaris2.11".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...
[New LWP 1]
[New LWP 1]
[Thread debugging using libthread_db enabled]
[New Thread 1 (LWP 1)]
Core was generated by `./a.out'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00000001000031c8 in c7_rbnode_init (node=0x100104152) at codr7/rbnode.c:7
7         node->left = node->right = NULL;
[Current thread is 3 (Thread 1 (LWP 1))]
(gdb) bt
#0  0x00000001000031c8 in c7_rbnode_init (node=0x100104152) at codr7/rbnode.c:7
#1  0x00000001000038f8 in c7_rbpool_get (pool=0xffffffff7ffff798) at codr7/rbpool.c:37
#2  0x0000000100003488 in c7_rbnode_add (node=0x0, tree=0xffffffff7ffff780, key=0xffffffff7ffff758, value=0xffffffff7ffff698) at codr7/rbnode.c:64
#3  0x0000000100003ad8 in c7_rbtree_add (tree=0xffffffff7ffff780, key=0xffffffff7ffff758) at codr7/rbtree.c:22
#4  0x0000000100002514 in rbtree_tests () at tests.c:76
#5  0x000000010000271c in main () at tests.c:95
(gdb) quit
```

**Comment by codr7** [comment]
Sorry, not getting how the code depends on endianess.
Could this be related to the alignment issue that I just fixed?

**Comment by tankf33der** [comment]
Works now.
